

# This file was *autogenerated* from the file Example1.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5)# This is valid Sage syntax
x = _sage_const_2 
y = x**_sage_const_3  + _sage_const_5    # Note: '^' is exponentiation in Sage, unlike Python's '**'
print(y)

