

# This file was *autogenerated* from the file Example2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1)# Define a variable in Sage
a = var('a')  # Creates a symbolic variable and assigns it to 'a'

# Define a polynomial ring
R = PolynomialRing(QQ, names=('x',)); (x,) = R._first_ngens(1)# Creates a polynomial ring R in variable x over the rational numbers QQ

# Define a polynomial
f = sin(x)  # Creates a polynomial f in the ring R

# Evaluate the polynomial at a specific value
result = f(_sage_const_1 )  # Evaluates f at x=1
print(result)  # Output: 6

