"""
MLE on 3 bits for g:{0,1}^3 -> F:
    g(0,0,0) = 0, and g(b) = 1 otherwise.
We build its multilinear extension  1 - (1 - x1)(1 - x2)(1 - x3)
and verify it matches g on the Boolean cube.
"""


# This file was *autogenerated* from the file MLE_3bits.sage
from sage.all_cmdline import *   # import sage library

_sage_const_101 = Integer(101); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
F = GF(_sage_const_101 )  # any field containing {0,1} works
R = PolynomialRing(F, names=('x1', 'x2', 'x3',)); (x1, x2, x3,) = R._first_ngens(3)

# multilinear extension from the closed form in the note
g_tilde = _sage_const_1  - (_sage_const_1  - x1) * (_sage_const_1  - x2) * (_sage_const_1  - x3)
print("g_tilde =", g_tilde)

# original Boolean function
def g(b1, b2, b3):
    return F(_sage_const_0 ) if (b1, b2, b3) == (_sage_const_0 , _sage_const_0 , _sage_const_0 ) else F(_sage_const_1 )

# check the MLE on all Boolean inputs
print("\nCheck on {0,1}^3:")
for b1 in (_sage_const_0 , _sage_const_1 ):
    for b2 in (_sage_const_0 , _sage_const_1 ):
        for b3 in (_sage_const_0 , _sage_const_1 ):
            lhs = g_tilde(F(b1), F(b2), F(b3))
            rhs = g(b1, b2, b3)
            print(f"{(b1, b2, b3)} -> g_tilde={lhs}, g={rhs}")

